---
name: CI

"on":
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/cachix-action@v15
        with:
          name: flake-fi6s
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          skipPush:
            ${{ !(github.ref == 'refs/heads/main') }}

      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v8

      - run: nix flake check -L

      - name: Check Nix flake Nixpkgs inputs
        uses: DeterminateSystems/flake-checker-action@main
        with:
          fail-mode: true
          ignore-missing-flake-lock: false


  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/cachix-action@v15
        with:
          name: flake-fi6s
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          skipPush:
            ${{ !(github.ref == 'refs/heads/main') }}

      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v8

      - run: nix build .
